models.py
# models.py
import sqlite3
from collections import defaultdict

def obtener_conexion(db_path):
   conn = sqlite3.connect(db_path)
   conn.row_factory = sqlite3.Row
   return conn

def obtener_datos(db_path):
    conn = obtener_conexion(db_path)
    cursor = conn.cursor()

    # Obtener clientes
    cursor.execute("SELECT * FROM clientes_con_deuda")
    clientes = [dict(row) for row in cursor.fetchall()]
    
    # Obtener vendedores
    cursor.execute("SELECT * FROM vendedores")
    vendedores = [dict(row) for row in cursor.fetchall()]

    # Obtener facturas
    cursor.execute("SELECT * FROM facturas_abiertas")
    invoices = [dict(row) for row in cursor.fetchall()]
    
    conn.close()
    
    vendedores_map = {v['SalesEmployeeCode']: v for v in vendedores}

    facturas_por_cliente = defaultdict(list)
    for invoice in invoices:
        card_code = invoice.get('CardCode')
        try:
           invoice['PaidToDate'] = float(invoice.get('PaidToDate', 0))
        except (ValueError, TypeError):
          invoice['PaidToDate'] = 0
        facturas_por_cliente[card_code].append(invoice)
    clientes_con_info = []
    for cliente in clientes:
        vendedor_code = cliente.get('SalesPersonCode')
        vendedor = vendedores_map.get(vendedor_code)
        
        saldos_por_categoria = {
            'En Fecha': 0,
            'Proxima a Vencer': 0,
            'Vencida': 0
        }
         
        total_saldo = 0
        for factura in facturas_por_cliente.get(cliente.get('CardCode'), []):
            saldo_pendiente = factura.get('SaldoPendiente',0)
            clasificacion = factura.get('Clasificacion')
            total_saldo += saldo_pendiente
            if clasificacion in saldos_por_categoria:
               saldos_por_categoria[clasificacion] += saldo_pendiente

        saldo_vencido = saldos_por_categoria['Vencida']
        porcentaje_vencido = (saldo_vencido / total_saldo) * 100 if total_saldo else 0
       
        cliente_info = {
            'CardCode': cliente.get('CardCode'),
            'CardName': cliente.get('CardName'),
            'CurrentAccountBalance': cliente.get('CurrentAccountBalance'),
            'vendedor': vendedor.get('SalesEmployeeName') if vendedor else "Sin Vendedor Asignado",
            'vendedor_code': vendedor_code if vendedor else None,
             'facturas': facturas_por_cliente.get(cliente.get('CardCode'), []),
            'saldos_por_categoria': saldos_por_categoria,
            'porcentaje_vencido': porcentaje_vencido
        }
        clientes_con_info.append(cliente_info)

        
        
    # Agrupar información por vendedor
    vendedores_con_saldos = []
    for vendedor in vendedores:
        vendedor_code = vendedor.get('SalesEmployeeCode')
        
        saldos_por_categoria_vendedor = {
             'En Fecha': 0,
             'Proxima a Vencer': 0,
            'Vencida': 0
         }
        total_saldo_vendedor = 0
        clientes_del_vendedor = [c for c in clientes_con_info if c.get('vendedor_code') == vendedor_code]
        for cliente in clientes_del_vendedor:
              for categoria,saldo in cliente.get('saldos_por_categoria').items():
                  saldos_por_categoria_vendedor[categoria] += saldo
              total_saldo_vendedor += cliente.get('CurrentAccountBalance',0)
          
        saldo_vencido_vendedor = saldos_por_categoria_vendedor['Vencida']
        porcentaje_vencido_vendedor = (saldo_vencido_vendedor / total_saldo_vendedor) * 100 if total_saldo_vendedor else 0

        vendedor_info = {
           'SalesEmployeeCode': vendedor.get('SalesEmployeeCode'),
           'SalesEmployeeName': vendedor.get('SalesEmployeeName'),
           'saldos_por_categoria': saldos_por_categoria_vendedor,
           'total_saldo':total_saldo_vendedor,
           'porcentaje_vencido':porcentaje_vencido_vendedor
        }
        vendedores_con_saldos.append(vendedor_info)
    vendedores_con_saldos = [vendedor for vendedor in vendedores_con_saldos if vendedor['total_saldo'] > 0]


    return clientes_con_info, vendedores, vendedores_con_saldos

app.py
# app.py
from routes import app
from scheduler import scheduler
import logging
from asgiref.wsgi import WsgiToAsgi #Importante

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

if __name__ == '__main__':
    logging.info("Iniciando el scheduler...")
    scheduler.start()

    try:
        logging.info("Servidor Flask iniciado por Uvicorn...")
    except Exception as e:
        logging.error(f"Error al iniciar el servidor Flask: {e}")
    finally:
        logging.info("Deteniendo el scheduler")
        scheduler.shutdown()

asgi_app = WsgiToAsgi(app) 


#### Se corre con :
# 
# 
# uvicorn app:asgi_app --host 0.0.0.0 --port 5010 --workers 4

controllers.py
# controllers.py
from flask import Blueprint, render_template, request
from services import get_data, update_data_service, generate_and_send_reports
from utils import format_number
import logging

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')

routes_blueprint = Blueprint('routes', __name__)

@routes_blueprint.route('/')
def index():
    clientes = get_data()[0]
    return render_template('index.html', clientes=clientes)

@routes_blueprint.route('/cliente/<string:card_code>')
def cliente_detail(card_code):
    clientes = get_data()[0]
    cliente = next((c for c in clientes if c['CardCode'] == card_code), None)
    if cliente:
        return render_template('cliente_detail.html', cliente=cliente)
    else:
        return "Cliente no encontrado", 404

@routes_blueprint.route('/vendedores')
def vendedores_list():
    vendedores = get_data()[1]
    return render_template('vendedores.html', vendedores=vendedores)

@routes_blueprint.route('/vendedores_con_saldos')
def vendedores_con_saldos_list():
    vendedores_con_saldos = get_data()[2]
    return render_template('vendedores_con_saldos.html', vendedores=vendedores_con_saldos)
   
@routes_blueprint.route('/dashboard')
def dashboard():
    clientes_con_info, _, vendedores_con_saldos = get_data()
    total_deuda = sum(cliente.get('CurrentAccountBalance', 0) or 0 for cliente in clientes_con_info)

    saldos_por_categoria_clientes = {
      'En Fecha':0,
      'Proxima a Vencer':0,
      'Vencida':0,
    }
    for cliente in clientes_con_info:
       for categoria,saldo in cliente.get('saldos_por_categoria').items():
          saldos_por_categoria_clientes[categoria] += saldo

    labels_vendedores = [vendedor.get('SalesEmployeeName') for vendedor in vendedores_con_saldos]
    deudas_vendedores = [vendedor.get('total_saldo',0) for vendedor in vendedores_con_saldos]
  
    return render_template('dashboard.html', 
                           total_deuda=total_deuda, 
                           saldos_por_categoria_clientes=saldos_por_categoria_clientes,
                           labels_vendedores = labels_vendedores,
                           deudas_vendedores = deudas_vendedores
                           )

@routes_blueprint.route('/update_data', methods=['POST'])
def update_data():
    try:
       message, message_type = update_data_service()
       return render_template('update_result.html', message=message, message_type=message_type), 200
    except Exception as e:
        logging.error(f"Error updating data: {e}")
        return render_template('update_result.html', message="Error al actualizar los datos.", message_type="error"), 500

@routes_blueprint.route('/generate_reports', methods=['POST'])
def generate_reports():
  try:
      clientes_con_info, vendedores,_ = get_data()
      result = generate_and_send_reports(vendedores, clientes_con_info, format_number)
      if "Error" in result:
         return render_template('report_result.html', message=result, message_type="error"), 500
      return render_template('report_result.html', message=result, message_type="success")
  except Exception as e:
        logging.error(f"Error generating reports: {e}")
        return render_template('report_result.html', message="Error al generar reportes.", message_type="error"), 500

routes.py
# routes.py
from flask import Flask
from controllers import routes_blueprint
from config import Config
from utils import format_number 

app = Flask(__name__)
app.config.from_object(Config)
app.register_blueprint(routes_blueprint)

app.jinja_env.filters['format_number'] = format_number 

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5010)

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="{{ url_for('static', filename='logo.png') }}" type="image/jpeg">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('routes.dashboard') }}">

            <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo" style="height: 60px; margin-right: 30px; margin-left: 25%;">
        </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
           <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('routes.index') }}">
                    <i class="fas fa-dollar-sign"></i> Saldo Clientes
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('routes.vendedores_con_saldos_list') }}">
                    <i class="fas fa-dollar-sign"></i> Saldo Vendedores
                </a>
            </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('routes.vendedores_list') }}">
                        <i class="fas fa-user"></i>  Vendedores
                    </a>
                </li>


            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
   <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/cliente_detail.html
{% extends 'base.html' %}

{% block title %}Detalle de Cliente{% endblock %}

{% block content %}
<style>
    .container {
    padding: 10px;
    }
    @media (max-width: 767px) {
        .clasificacion {
        display: block;
        margin-bottom: 5px;
       }
    }
</style>
    <div class="container">
        <div class="d-flex align-items-start">
            <div class="mb-3 me-4" style="flex: 1;">
                <h2>Detalle de Cliente: <strong> {{ cliente.CardName }}</strong></h2>
                <br><br>
                <p><strong>Código:</strong> {{ cliente.CardCode }}</p>
                <p><strong>Vendedor: {{ cliente.vendedor }}</strong> </p>
                <p><strong>Saldo:$ {{ cliente.CurrentAccountBalance | format_number }}</strong> </p>
            </div>
            <div style="width: 35%; min-width:300px; max-width:700px; margin-top: 8%; margin-right: 5%;">
               <canvas id="clasificacionChart"></canvas>
           </div>
       </div>

        <h3>Facturas Pendientes</h3>
        {% if cliente.facturas %}
            <table id="facturas-table" class="table table-striped">
                <thead>
                    <tr>
                        <th>Número</th>
                        <th>Fecha</th>
                        <th>Vencimiento</th>
                        <th data-type="num-fmt">Total</th>
                        <th data-type="num-fmt">Aplicado</th>
                        <th data-type="num-fmt">Saldo</th>
                        <th>Días</th>
                        <th>Clasificación</th>
                    </tr>
                </thead>
                <tbody id="facturas-table-body">
                    {% for factura in cliente.facturas %}
                        <tr>
                            <td>{{ factura.NumAtCard }}</td>
                            <td class="fecha-formateada">{{ factura.DocDate }}</td>
                            <td class="fecha-formateada-vencimiento">{{ factura.DocDueDate }}</td>
                            <td data-order="{{ factura.DocTotal }}">$ {{ factura.DocTotal | format_number}}</td>
                            <td data-order="{{ factura.PaidToDate if factura.PaidToDate is number else 0 }}">
                                {% if factura.PaidToDate is number %}
                                    $ {{ factura.PaidToDate | format_number}}
                                {% else %}
                                     N/A
                                {% endif %}
                            </td>
                            <td data-order="{{ factura.SaldoPendiente if factura.SaldoPendiente is number else 0 }}">
                                {% if factura.SaldoPendiente is number %}
                                    $ {{ factura.SaldoPendiente | format_number}}
                                {% else %}
                                     N/A
                                {% endif %}
                            </td>
                            <td>{{ factura.DiasDesdeCreacion }}</td>
                            <td >
                                 {% if factura.Clasificacion == 'En Fecha' %}
                                    <span class="clasificacion en-fecha">{{ factura.Clasificacion }}</span>
                                {% elif factura.Clasificacion == 'Proxima a Vencer' %}
                                    <span class="clasificacion proxima-vencer">{{ factura.Clasificacion }}</span>
                                {% elif factura.Clasificacion == 'Vencida' %}
                                    <span class="clasificacion vencida">{{ factura.Clasificacion }}</span>
                                {% else %}
                                    {{ factura.Clasificacion }} 
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay facturas pendientes para este cliente.</p>
        {% endif %}


        <a href="{{ url_for('routes.index') }}" class="btn btn-secondary">Volver al listado de clientes</a>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    $(document).ready( function () {
         $.fn.dataTable.ext.type.order['num-fmt-pre'] = function (a) {
             let number= parseFloat(a.replace(/[^0-9,-]/g, '').replace(',','.'))
            return isNaN(number) ? 0 : number;
        };
        $('#facturas-table').DataTable({
             "language": {
                "url": "{{ url_for('static', filename='Spanish.json') }}"
            },
              columnDefs: [
                { type: 'num-fmt', targets: 3 },
                {
                    targets: [1, 2],
                    render: function (data) {
                        if (data) {
                            const date = new Date(data);
                             return date.toLocaleDateString();
                        } else {
                         return "";
                         }
                    }
                }
              ]
        });

         // Obtener los datos de la tabla
        const facturasData = [];
        $('#facturas-table-body tr').each(function() {
            const clasificacion = $(this).find('td:eq(7)').text().trim();
            const saldo = parseFloat($(this).find('td:eq(5)').attr('data-order') || 0); // Obtiene el valor numerico de data-order, sino es 0

            facturasData.push({ clasificacion, saldo });
        });

        // Procesar los datos para el gráfico
        const saldosPorClasificacion = facturasData.reduce((acc, factura) => {
            acc[factura.clasificacion] = (acc[factura.clasificacion] || 0) + factura.saldo;
            return acc;
        }, {});

        // Define el orden de clasificación y sus colores
        const clasificacionesOrdenadas = ['En Fecha', 'Proxima a Vencer', 'Vencida'];
        const coloresOrdenados = [
            'green',  // Verde
            'orange',  // Amarillo
            'red'   // Rojo
        ];
         const bordesOrdenados = [
             'rgb(75, 192, 192)',   // Verde
            'rgb(255, 205, 86)',     // Amarillo
             'rgb(255, 99, 132)'    // Rojo
        ];

        // Extrae los saldos en el orden correcto
        const saldos = clasificacionesOrdenadas.map(clasificacion => saldosPorClasificacion[clasificacion] || 0);
        
        // Crear el gráfico
        const ctx = document.getElementById('clasificacionChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: clasificacionesOrdenadas,
                datasets: [{
                    label: 'Saldo por Clasificación',
                    data: saldos,
                    backgroundColor: coloresOrdenados,
                     borderColor: bordesOrdenados,
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    } );
</script>
{% endblock %}

templates/dashboard.html
<!-- templates/dashboard.html -->
{% extends 'base.html' %}

{% block title %}Dashboard de Cobranzas{% endblock %}

{% block content %}
    <h2>Dashboard de Cobranzas</h2>
    <br><br>
    <div class="row">
    <div class="col-md-6">
        <h3>Total de Deuda: ${{ total_deuda | format_number}}</h3>
        <canvas id="deudaPorCategoriaChart"></canvas>
    </div>
     <div class="col-md-6">
           <h3>Deuda por Vendedor</h3>
         <canvas id="deudaVendedorChart"></canvas>
     </div>
    </div>
    

    <li class="nav-item">
        <!-- Botón de Actualizar Datos -->
        <form method="post" action="{{ url_for('routes.update_data') }}">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-sync-alt"></i> Actualizar Datos
            </button>
        </form>
    </li>

    <br>
    <form action="/generate_reports" method="post" >
        <button type="submit" class="btn btn-primary">Generar y Enviar Reportes</button>
      </form>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
         // Datos para el gráfico de deuda por categoria de cliente
        const saldosCategorias = JSON.parse('{{ saldos_por_categoria_clientes | tojson | safe }}');
        const labelsCategorias = Object.keys(saldosCategorias);
        const saldos = Object.values(saldosCategorias);
        const coloresOrdenados = [
            'green',  // Verde
            'orange',  // Amarillo
            'red'   // Rojo
        ];
         const bordesOrdenados = [
             'rgb(75, 192, 192)',   // Verde
            'rgb(255, 205, 86)',     // Amarillo
             'rgb(255, 99, 132)'    // Rojo
        ];
        // Configuración del gráfico de deuda por categorias de cliente
        const ctxDeudaPorCategoria = document.getElementById('deudaPorCategoriaChart').getContext('2d');
        const deudaPorCategoriaChart = new Chart(ctxDeudaPorCategoria, {
                type: 'bar',
                data: {
                    labels: labelsCategorias,
                     datasets: [{
                        label: 'Deuda por Categoría',
                        data: saldos,
                        backgroundColor: coloresOrdenados,
                         borderColor: bordesOrdenados,
                        borderWidth: 1
                      }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                         },
                          plugins: {
                               tooltip: {
                                    callbacks: {
                                        label: function(context) {
                                            let label = context.dataset.label || '';
                                            if (label) {
                                            label += ': ';
                                            }
                                          label += 'S/ ' + context.formattedValue;
                                        return label
                                        },
                                        title: function(context){
                                            const index = context[0].dataIndex;
                                            const label = context[0].label;
                                            return label;
                                        },
                                    }
                                 }
                            },
                         
                      }
            });

          // Datos para el gráfico de deuda por vendedor
         const labelsVendedores = JSON.parse('{{ labels_vendedores | tojson | safe}}');
         const deudasVendedores = JSON.parse('{{ deudas_vendedores | tojson | safe }}');
         
        // Configuración del gráfico de deuda por vendedor
        const ctxDeudaVendedor = document.getElementById('deudaVendedorChart').getContext('2d');
        const deudaVendedorChart = new Chart(ctxDeudaVendedor, {
            type: 'bar',
            data: {
                labels: labelsVendedores,
                datasets: [{
                    label: 'Deuda por Vendedor',
                    data: deudasVendedores,
                    backgroundColor: 'blue',
                    borderColor: 'rgb(102, 196, 255)',
                    borderWidth: 1
                }]
            },
             options: {
                 scales: {
                    y: {
                       beginAtZero: true
                       }
                    },
                    plugins: {
                         tooltip: {
                                  callbacks: {
                                     label: function(context) {
                                            let label = context.dataset.label || '';
                                           if (label) {
                                               label += ': ';
                                            }
                                           label += 'S/ ' + context.formattedValue;
                                            return label;
                                          },
                                       title: function(context){
                                             const index = context[0].dataIndex;
                                            const label = context[0].label;
                                            return label;
                                          },
                                      }
                                }
                           },
                }
        });
    });
</script>


{% endblock %}

templates/index.html
<!--templates\index.html (Saldo de Clientes)-->
{% extends 'base.html' %}

{% block title %}Listado de Clientes{% endblock %}

{% block content %}
    <h2>Listado de Clientes con Saldo</h2>
    <table id="clientes-table" class="table">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nombre</th>
                <th>Vendedor</th>
                <th data-type="num-fmt">Saldo</th>
                <th data-type="num-fmt">En Fecha</th>
                <th data-type="num-fmt">Próxima a Vencer</th>
                <th data-type="num-fmt">Vencida</th>
                 <th data-type="num-fmt">% Vencido</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            {% if cliente.CardCode %}
            <tr>
                <td>{{ cliente.CardCode }}</td>
                <td>{{ cliente.CardName }}</td>
                <td>{{ cliente.vendedor }}</td>
                <td data-order="{{ cliente.CurrentAccountBalance }}">$ {{ cliente.CurrentAccountBalance | format_number }}</td>
                
               <td data-order="{{ cliente.saldos_por_categoria['En Fecha'] }}"
                    {% if cliente.saldos_por_categoria['En Fecha'] > 0 %}
                       class="saldo-en-fecha"
                   {% endif %}>
                     $ {{ cliente.saldos_por_categoria['En Fecha'] | format_number }}
                </td>
                   
                <td data-order="{{ cliente.saldos_por_categoria['Proxima a Vencer'] }}"
                    {% if cliente.saldos_por_categoria['Proxima a Vencer'] > 0 %}
                    class="saldo-proxima-vencer"
                    {% endif %}>
                    $ {{ cliente.saldos_por_categoria['Proxima a Vencer'] | format_number }}
                </td>
                
                <td data-order="{{ cliente.saldos_por_categoria['Vencida'] }}"
                    {% if cliente.saldos_por_categoria['Vencida'] > 0 %}
                    class="saldo-vencida"
                    {% endif %}>
                    $ {{ cliente.saldos_por_categoria['Vencida'] | format_number }}
                </td>
                <td data-order="{{ cliente.porcentaje_vencido }}">{{ cliente.porcentaje_vencido | format_number }}%</td>
                <td><a href="{{ url_for('routes.cliente_detail', card_code=cliente.CardCode) }}">Detalle</a></td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <script id="data-clientes" type="application/json">
        {{ clientes | tojson }}
    </script>
    <button id="export-excel" class="btn btn-primary mb-2">Descargar Excel</button>

{% endblock %}

{% block styles %}
  <style>
    .saldo-en-fecha {
      background-color: #a6f2a6;
    }
    .saldo-proxima-vencer {
      background-color: #f2f2a6;
    }
    .saldo-vencida {
      background-color: #f2a6a6;
    }
  </style>
{% endblock %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<script>
    $(document).ready( function () {
        var table = $('#clientes-table').DataTable({
            "language": {
               "url": "{{ url_for('static', filename='Spanish.json') }}"
           }
          
        });
          $('#export-excel').on('click', function() {
          exportTableToExcel(table, 'Listado de Clientes');
      });

    });

   function exportTableToExcel(table, filename = ''){
        // Obtener los datos del script
         var data_json =  $('#data-clientes').text()
          var data = JSON.parse(data_json)
        
        // Crear un array para los encabezados
        var headers = [];
        $('#clientes-table thead th').each(function() {
            headers.push($(this).text());
        });

        // Crear un array con los datos y encabezados
        var excelData = [headers];
         
        data.forEach(cliente => {
            var rowData = [];
             rowData.push(cliente.CardCode);
             rowData.push(cliente.CardName);
             rowData.push(cliente.vendedor);
             rowData.push(cliente.CurrentAccountBalance);
             rowData.push(cliente.saldos_por_categoria['En Fecha']);
             rowData.push(cliente.saldos_por_categoria['Proxima a Vencer']);
             rowData.push(cliente.saldos_por_categoria['Vencida']);
             rowData.push(cliente.porcentaje_vencido);
            excelData.push(rowData)
        })
       
        // Crear el libro de Excel y la hoja
          var wb = XLSX.utils.book_new();
          var ws = XLSX.utils.aoa_to_sheet(excelData);
          XLSX.utils.book_append_sheet(wb, ws, "Sheet1");


          XLSX.writeFile(wb, filename + '.xlsx');
      }

</script>
{% endblock %}

templates/report_result.html
<!-- templates/report_result.html -->
{% extends 'base.html' %}

{% block title %}Generación de Reportes{% endblock %}

{% block content %}
    <h1>Resultado de la Generación de Reportes</h1>
    
    {% if message %}
        <div class="message-container {{ message_type }}">
            {{ message }}
        </div>
    {% endif %}
    
    <!-- Puedes agregar contenido adicional aquí, si es necesario -->
    <a href="{{ url_for('routes.index') }}">Volver a la página principal</a>
{% endblock %}

{% block scripts %}
    <!-- Puedes añadir scripts específicos para esta página aquí si es necesario-->
{% endblock %}

templates/update_result.html
<!-- templates/update_result.html -->
{% extends 'base.html' %}

{% block title %}Actualización{% endblock %}

{% block content %}
    <h3>Resultado de la Actualización :</h3>
    
    {% if message %}
        <div class="message-container {{ message_type }}" >
            <h1>{{ message }}</h1>
        </div>
    {% endif %}
    
    <!-- Puedes añadir más contenido aquí, si es necesario -->
    <a href="{{ url_for('routes.dashboard') }}"> Volver a la página principal </a>
{% endblock %}

{% block scripts %}
    <!-- Puedes añadir scripts específicos para esta página aquí si es necesario-->
{% endblock %}